export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"

// historiques
export const HISTORIQUE_LOADED_SUCCESS = "HISTORIQUE_LOADED_SUCCESS"
export const HISTORIQUE_LOADED_FAILED = "HISTORIQUE_LOADED_FAILED"

// comptes
export const COMPTES_LOADED_SUCCESS = "COMPTES_LOADED_SUCCESS"
export const COMPTES_LOADED_FAILED = "COMPTES_LOADED_FAILED"

// operations
export const OPERATION_LOADED_SUCCESS = "OPERATION_LOADED_SUCCESS"
export const OPERATION_LOADED_FAILED = "OPERATION_LOADED_FAILED"